name: Android APK Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm install --force

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Release APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk


      - name: Send APK via Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.resend.com
          server_port: 587
          username: apikey
          password: ${{ secrets.RESEND_API_KEY }}
          subject: 'New APK Build 📦'
          body: |
            Hi Team,

            A new Android APK build has been generated successfully! 🎉

            Please find the APK attached.

            Thanks,
            GitHub Actions Bot 🤖
          to: anamfirdaus04@gmail.com,mohammadamansari777@gmail.com,mohammadaffan777@gmail.com,yashfeennashra@gmail.com
          from: mohammadaffan777@gmail.com
          attachments: android/app/build/outputs/apk/release/app-release.apk